//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.det_producto = new HashSet<det_producto>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<double> precio_compra { get; set; }
        public Nullable<double> precio_venta { get; set; }
        public string tipo { get; set; }
        public Nullable<int> stock { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<det_producto> det_producto { get; set; }
    }
}
